site_name: x86prime
nav:
    - Home: index.md
    - x86prime: x86prime.md
    - Afviklingsplot:
        - Introduktion: afviklingsplot/index.md
        - Superskalar: afviklingsplot/superscalar.md
        - Anonyme Faser: afviklingsplot/anonyme.md
        - Out-of-order: afviklingsplot/out-of-order.md
        - Kontrol afhængigheder: afviklingsplot/kontrol.md
theme: readthedocs
