site_name: x86prime
nav:
    - Home: index.md
    - x86prime: x86prime.md
    - Afviklingsplot:
        - Introduktion: afviklingsplot/index.md
        - Simpel pipeline: afviklingsplot/pipeline.md
        - Superskalar: afviklingsplot/superscalar.md
        - Avanceret pipeline, anonyme faser: afviklingsplot/anonyme.md
        - Out-of-order: afviklingsplot/out-of-order.md
        - Kontrol afhængigheder: afviklingsplot/kontrol.md
theme: readthedocs
extra_css:
    - css/extra.css
